require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rspec
  - rubocop-thread_safety

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Performance/Casecmp:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: never

# Style/MixinUsage:
#   Exclude:
#     - bin/*
