require:
  # - rubocop-factory_bot
  # - rubocop-graphql
  # - rubocop-i18n
  # - rubocop-md
  - rubocop-performance
  # - rubocop-rails
  # - rubocop-rspec
  # - rubocop-thread_safety

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable
  # Exclude:
  #   - db/schema.rb
  #   - vendor/bundle/**/*
  #   - bin/*
  #   - lib/pub_sub/schemas/**/*_pb.rb

Performance/Casecmp:
  Enabled: false

Performance/RegexpMatch:
  Enabled: false

Style/AsciiComments:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: never

# Style/MixinUsage:
#   Exclude:
#     - bin/*
