require:
  - rubocop-md
  - rubocop-performance
  - rubocop-rake
  - rubocop-rspec
  - rubocop-thread_safety

inherit_from: .rubocop_todo.yml

AllCops:
  NewCops: enable

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  EnforcedStyle: never

Style/HashSyntax:
  EnforcedStyle: ruby19
  EnforcedShorthandSyntax: never

Style/WordArray:
  Exclude:
    - spec/support/schema.rb
