source "https://rubygems.org"

gemspec name: "this_feature"
gemspec name: "this_feature-adapters-flipper"
gemspec name: "this_feature-adapters-split_io"

gem "bundler"
gem "database_cleaner-active_record"
gem "gem-release"
gem "rake"
gem "rspec"
gem "rubocop"
gem "rubocop-md"
gem "rubocop-performance"
gem "rubocop-rspec"
gem "rubocop-thread_safety"
gem "sqlite3"
