class FFeature
  module Adapters
    class FakeAdapter < BaseAdapter

      # DONT ADD ANY FUNCTIONALITY HERE OTHER THAN THE SETUP METHOD
      # THIS ADAPTER SHOULD HAVE ALL ITS FUNCTIONALITY ADDED THROUGH STUBS.
      # CALLING METHODS ON IT DIRECTLY WILL INTENTIONALLY RAISE UNIMPLEMENTED ERRORS.

      def self.setup; end

    end
  end
end
