on: [push]

name: Test

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Set up Ruby
        uses: ruby/setup-ruby@master
        with:
          bundler-cache: true

      - name: Run RSpec
        run:  bundle exec rspec
